version: '3.3'
services:
    schema:
        image: dbmi/i2b2-data:1.7.09c
        environment:
            - DB_TYPE=${DB_TYPE}
            - DB_HOST=db
            - DB_PORT=1521
            - DB_ORASVC=ORCLPDB1
            - DB_USER=pdbadmin
            - DB_PASSWORD=password
        #networks:
            #- public

    #db:
        #image: dbmi/${DB_TYPE}:${DB_VERSION}
        #environment:
            # used to initialize system passwords
            #- DB_PASSWORD=password
        #networks:
            ## public network used to access DB from outside (e.g. SQLDeveloper)
            #- public
        #volumes:
            ## TODO: eventually remove this as a volume and add it
            ## to the dbmi/oracle base image -Andr
            #- ./startup:/opt/oracle/scripts/startup:ro
        #expose:
            #- 1521
        #ports:
            #- 1521:1521



#networks:
    #public:
