version: '3.3'
services:

    db:
        image: dbmi/i2b2transmart-db:${DB_VERSION}
        networks:
            - public
        expose:
            - 1521
        ports:
            - ${DOCKER_DB_PORT}:1521


networks:
    public:
