version: '3.3'
services:

  # nginx
  nginx:
    image: dbmi/nginx:${nginx_version}
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
      - "edu.hms.harvard.dbmi.stack.env=${STACK_ENV}"
    restart: always
    # application stack exposed ports
    ports:
      - 80:80
      - 443:443
    networks:
      - public


  ## PIC-SURE API Stack ##
  # IRCT
  irct:
    image: dbmi/irct:${irct_version}
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
      - "edu.hms.harvard.dbmi.stack.env=${STACK_ENV}"
    depends_on:
       - nginx
    env_file:
      - ${ENV_FILE}
    # debug command
    command: --debug --server-config=standalone.xml
    restart: always
    networks:
      - public
    expose:
      - 8080
    ports:
      # debug port
      - 8787:8787
    volumes:
      - ${LOCAL_IRCT}/IRCT-CL.war:/opt/jboss/wildfly/standalone/deployments/IRCT-CL.war:cached

  irct-init:
    image: dbmi/irct-init:${irct_init_version}
    env_file:
      - ${ENV_FILE}
    networks:
      - public

networks:
    public:
